# Generated by Django 4.2.17 on 2024-12-22 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_unique_booking_booking_unique_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking',
        ),
    ]
